### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by coltonrobbins73** [coltonrobbins73/self_stats#1]
- [ ]  Plot ideas for visualizing **web traffic data**
  - [ ] Look for pre-existing libraries
  - [ ] Draw on existing web traffic analytics frameworks
  - [ ] Current ideas
    - [x] Day of the week activity profile
    - [x] Long term activity profile
    - [ ] Keyword graph display of common search categories
    - [ ] Heat map of where you submit queries using lat and long coords
- [ ] Plot ideas for visualizing **youtube watch history**
  - [ ] Common video themes over time
- [ ] Plot ideas for visualizing **calendar events**
- [ ] Plot ideas for visualizing other data **flights, notifications, podcasts, maps**
- [ ] Plot ideas for visualizing **phone calls, voicemail, chats**
  - [ ] Overall activity over time
- [ ] Write better documentation
  - [ ] Currently using automated generation with sphinx
- [ ] Package application with pip

**Comment by coltonrobbins73** [comment]
Ideas for text data visualization

- [ ] Word cloud of most common topics with color and size emphasis
- [ ] Network diagram of related words
- [ ] Drill down network
- [ ] Hive network
- [ ] Topic modeling (gensim, sickit-learn)
- [ ] Query characteristics like overall length or word count
